server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: zuul-part-9000
#    # 表示是否将自己注册到Eureka Server，默认为true
#    register-with-eureka: false
#    # 表示是否从Eureka Server获取注册信息
#    fetch-registry: false
spring:
  application:
    name: kyn-zuul-part
zuul:
  routes:
    consumer-depart-8090: /kyn8090/**
    consumer-depart-8080: /kyn8080/**