server:
  port: 8000
eureka:
  instance:
    hostname: localhost #指定主机的名称
  client:
    register-with-eureka: false #指定是否向注册中心注册自己
    fetch-registry: false #指定客户端是都能搜获取eureka注册信息
    service-url:    #暴露服务中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #等价于http://localhost:8080/eureka
  server:
    eviction-interval-timer-in-ms: 1000
  #enable-self-preservation: false
